CoreDemo/Areas/Admin/Models/WriterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace CoreDemo.Areas.Admin.Models
{
    [Area("Admin")]

    public class WriterController :Controller
    {
       public IActionResult Index()
        {
            return View();
        }

        public IActionResult WriterList()
        {
            var jsonWriters = JsonConvert.SerializeObject(writers);
            return Json(jsonWriters);
        }

        public IActionResult GetWriterByID(int id)
        {
            var findWriters = writers.FirstOrDefault(x => x.Id == id);
            var jsonWriters = JsonConvert.SerializeObject(findWriters);
            return Json(jsonWriters);
        }

        public IActionResult AddWriter(WriterClass w)
        {
            writers.Add(w);
            var jsonWriters = JsonConvert.SerializeObject(w);
            return Json(jsonWriters);
        }

        public IActionResult DeleteWriter(int id)
        {
            var writer = writers.FirstOrDefault(x => x.Id == id);
            writers.Remove(writer);
            return Json(writer);
        }

        public IActionResult UpdateWriter(WriterClass w)
        {
            var writer = writers.FirstOrDefault(x => x.Id == w.Id);
            writer.Name = w.Name;
            var jsonWriters = JsonConvert.SerializeObject(w);
            return Json(jsonWriters);
        }


        public static List<WriterClass> writers = new List<WriterClass>
        {
            new WriterClass
            {
                Id =1,
                Name ="Ayşe"
            },
             new WriterClass
            {
                Id =2,
                Name ="Ahmet"
            },
              new WriterClass
            {
                Id =3,
                Name ="Buse"
            },

        };
    }
}

CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class WriterController : Controller
    {
        WriterManager wm = new WriterManager(new EfWriterRepository());
        UserManager UserManager = new UserManager(new EfUserRepository());

        private readonly UserManager<AppUser> _userManager;

        public WriterController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            var usermail = User.Identity.Name;
            ViewBag.v = usermail;
            Context c = new Context();
            var writerName = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterName).FirstOrDefault();
            ViewBag.v2=writerName;
            return View();
        }

        public IActionResult WriterProfile() 
        {
            return View(); 
        }

        public IActionResult WriterMail()
        {
            return View();
        }
        public IActionResult Test()
        {
            return View();
        }

        public PartialViewResult WriterNavbarPartial()
        {
            return PartialView();
        }

        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }

        [HttpGet]
        public async Task<IActionResult> WriterEditProfileAsync()
        {
            //Context c = new Context();
            //var username = User.Identity.Name;
            //var usermail = c.Users.Where(x=>x.UserName == username).Select(y => y.Email).FirstOrDefault();
            //var writerID = c.Users.Where(x => x.Email == usermail).Select(y => y.Id).FirstOrDefault();

            //var writervalues = UserManager.TGetById(writerID);
            var writervalues = await _userManager.FindByNameAsync(User.Identity.Name);
            UserUpdateViewModel userUpdateViewModel = new UserUpdateViewModel();
            userUpdateViewModel.namesurname = writervalues.NameSurname;
            userUpdateViewModel.imageurl = writervalues.ImageUrl;
            userUpdateViewModel.mail = writervalues.Email;
            userUpdateViewModel.username = writervalues.UserName;
            return View(userUpdateViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> WriterEditProfile(UserUpdateViewModel p)
        {
            var values = await _userManager.FindByNameAsync(User.Identity.Name);
            values.NameSurname = p.namesurname;
            values.ImageUrl = p.imageurl;
            values.Name = p.username;
            values.Email = p.mail;
            values.PasswordHash = _userManager.PasswordHasher.HashPassword(values,"Emre123");
            var result = await _userManager.UpdateAsync(values);

            return RedirectToAction("Index", "Dashboard");
        }


        
     

        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w = new Writer();
            if(p.WriterImage != null)
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newimagename = Guid.NewGuid().ToString() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/", newimagename);
                var stream = new FileStream(location, FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newimagename;
            }
            w.WriterName = p.WriterName;
            w.WriterMail = p.WriterMail;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = true;
            w.WriterAbout = p.WriterAbout;
            wm.TAdd(w);
            return RedirectToAction("Index", "Dashboard");
        }


    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>Witer Index</h1>

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Test</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
     <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                     @Html.HiddenFor(x=>x.WriterId, new {@class = "form-control"})
                    <div class="forms-sample">
                      <div class="form-group">
                        <label for="exampleInputName1">Yazar Adı</label>
                        @Html.TextBoxFor(x=>x.WriterName, new {@class = "form-control"})
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                        @Html.TextBoxFor(x=>x.WriterMail, new {@class = "form-control"})
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.TextBoxFor(x=>x.WriterPassword, new {@class = "form-control"})
                      </div>
                     
                      <div class="form-group">
                        <label>Yazar Görsel</label>
                        <input type="file" name="WriterImage" >
                      </div>
                    
                      <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                        @Html.TextAreaFor(x=>x.WriterAbout,10,3, new {@class = "form-control"})
                      </div>
                      <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                      <button class="btn btn-light">İptal</button>
                    </div>
                  </div>
                </div>
              </div>
</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model UserUpdateViewModel
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post))
{
     <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                    
                    <form class="forms-sample">
                      <div class="form-group">
                        <label for="exampleInputName1">Yazar Adı</label>
                        <input  type="text" asp-for="@Model.namesurname" class = "form-control" /> 
                      </div>
                       <div class="form-group">
                        <label for="exampleInputName1">Kullanıcı Adı</label>
                        -<input  type="text" asp-for="@Model.username" class = "form-control" /> 

                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                       <input  type="text" asp-for="@Model.mail" class = "form-control" /> 

                      </div>
                     
                      <div class="form-group">
                        <label for="exampleInputEmail3">Şifre</label>
                       <input  type="text" asp-for="@Model.password" class = "form-control" /> 

                      </div>
                      <div class="form-group">
                        <label>Yazar Görsel</label>
                        <input type="file" name="img[]" class="file-upload-default">
                        <div class="input-group col-xs-12">
                          <input type="text" class="form-control file-upload-info" disabled placeholder="Resim">
                          <span class="input-group-append">
                            <button class="file-upload-browse btn btn-gradient-primary" type="button">Resim Seç</button>
                          </span>
                        </div>
                      </div>
                    
                    @*  <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                        @Html.TextAreaFor(x=>x.UserName,10,3, new {@class = "form-control"})
                      </div>*@
                      <button type="submit" class="btn btn-gradient-primary mr-2">Güncelle</button>
                      <button class="btn btn-light">İptal</button>
                    </form>
                  </div>
                </div>
              </div>
}

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
   <footer class="footer">
            <div class="container-fluid clearfix">
              <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Tüm Hakları Saklıdır | @DateTime.Now.Year</span>
              <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> 
                  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Core 5.0 Proje Kampı </a></span>
            </div>
          </footer>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
 <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item nav-profile">
              <a href="#" class="nav-link">
                <div class="nav-profile-image">
                  <img src="~/writer/assets/images/faces/face1.jpg" alt="profile">
                  <span class="login-status online"></span>
                  <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                  <span class="font-weight-bold mb-2">Yazar adı soyadı</span>
                  <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
        
            <li class="nav-item">
              <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Message/Inbox/">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-message menu-icon"></i>
              </a>
            </li>
           
           <li class="nav-item">
              <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
              </a>
            </li>

             <li class="nav-item">
              <a class="nav-link" href="~/writer/pages/tables/basic-table.html">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
              </a>
            </li>

             <li class="nav-item">
              <a class="nav-link" href="/Login/LogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout menu-icon"></i>
              </a>
            </li>

          </ul>
        </nav>